def boxes():
  return [
    {"id": 1, "especialidades": ["Ginecología", "Obstetricia"], "habilitado": True},
    {"id": 2, "especialidades": ["Medicina General"], "habilitado": True},
    {"id": 3, "especialidades": ["Pediatría"], "habilitado": True},
    {"id": 4, "especialidades": ["Otorrino"], "habilitado": True},
    {"id": 5, "especialidades": ["Cardiología"], "habilitado": True},
    {"id": 6, "especialidades": ["Dermatología"], "habilitado": True},
    {"id": 7, "especialidades": ["Neurología"], "habilitado": True},
    {"id": 8, "especialidades": ["Psiquiatría"], "habilitado": True},
    {"id": 9, "especialidades": ["Traumatología"], "habilitado": True},
    {"id": 10, "especialidades": ["Endocrinología"], "habilitado": False},
    {"id": 11, "especialidades": ["Ginecología"], "habilitado": True},
    {"id": 12, "especialidades": ["Medicina General"], "habilitado": True},
    {"id": 13, "especialidades": ["Pediatría"], "habilitado": True},
    {"id": 14, "especialidades": ["Otorrino"], "habilitado": True},
    {"id": 15, "especialidades": ["Cardiología"], "habilitado": True},
    {"id": 16, "especialidades": ["Dermatología"], "habilitado": True},
    {"id": 17, "especialidades": ["Neurología"], "habilitado": True},
    {"id": 18, "especialidades": ["Psiquiatría"], "habilitado": True},
    {"id": 19, "especialidades": ["Traumatología"], "habilitado": True},
    {"id": 20, "especialidades": ["Endocrinología"], "habilitado": True},
    {"id": 21, "especialidades": ["Oncología"], "habilitado": True},
    {"id": 22, "especialidades": ["Reumatología"], "habilitado": True},
    {"id": 23, "especialidades": ["Cirugía General"], "habilitado": True},
    {"id": 24, "especialidades": ["Neumología"], "habilitado": True},
    {"id": 25, "especialidades": ["Infectología"], "habilitado": True},
    {"id": 26, "especialidades": ["Urología"], "habilitado": True},
    {"id": 27, "especialidades": ["Traumatología"], "habilitado": True},
    {"id": 28, "especialidades": ["Oftalmología"], "habilitado": True},
    {"id": 29, "especialidades": ["Cardiología"], "habilitado": True},
    {"id": 30, "especialidades": ["Ginecología", "Obstetricia"], "habilitado": True},
    {"id": 31, "especialidades": ["Medicina General"], "habilitado": True},
    {"id": 32, "especialidades": ["Pediatría"], "habilitado": True},
    {"id": 33, "especialidades": ["Otorrino"], "habilitado": True},
    {"id": 34, "especialidades": ["Cardiología"], "habilitado": True},
    {"id": 35, "especialidades": ["Dermatología"], "habilitado": True},
    {"id": 36, "especialidades": ["Neurología"], "habilitado": True},
    {"id": 37, "especialidades": ["Psiquiatría"], "habilitado": True},
    {"id": 38, "especialidades": ["Traumatología"], "habilitado": True},
    {"id": 39, "especialidades": ["Endocrinología"], "habilitado": True},
    {"id": 40, "especialidades": ["Oncología"], "habilitado": True},
    {"id": 41, "especialidades": ["Reumatología"], "habilitado": True},
    {"id": 42, "especialidades": ["Cirugía General"], "habilitado": True},
    {"id": 43, "especialidades": ["Neumología"], "habilitado": True},
    {"id": 44, "especialidades": ["Infectología"], "habilitado": True},
    {"id": 45, "especialidades": ["Urología"], "habilitado": True},
    {"id": 46, "especialidades": ["Oncología"], "habilitado": True},
    {"id": 47, "especialidades": ["Oftalmología"], "habilitado": True},
    {"id": 48, "especialidades": ["Oftalmología", "Neumología"], "habilitado": True},
    {"id": 49, "especialidades": ["Cirugía General", "Cardiología"], "habilitado": True},
    {"id": 50, "especialidades": ["Endocrinología", "Reumatología"], "habilitado": True},
    {"id": 51, "especialidades": ["Neurocirugía"], "habilitado": True}
]
def medicos():
  return [
    {"nombre": "Dr. Juan Pérez", "especialidad": "Ginecología", "desde": "08:00", "hasta": "14:00"},
    {"nombre": "Dr. Laura González", "especialidad": "Medicina General", "desde": "08:00", "hasta": "14:00"},
    {"nombre": "Dr. Carlos Rodríguez", "especialidad": "Pediatría", "desde": "08:00", "hasta": "14:00"},
    {"nombre": "Dr. Ana López", "especialidad": "Otorrino", "desde": "08:00", "hasta": "14:00"},
    {"nombre": "Dr. Luis García", "especialidad": "Cardiología", "desde": "08:00", "hasta": "14:00"},
    {"nombre": "Dr. Beatriz Fernández", "especialidad": "Dermatología", "desde": "08:00", "hasta": "14:00"},
    {"nombre": "Dr. Roberto Díaz", "especialidad": "Neurología", "desde": "08:00", "hasta": "14:00"},
    {"nombre": "Dr. María Herrera", "especialidad": "Psiquiatría", "desde": "08:00", "hasta": "14:00"},
    {"nombre": "Dr. Miguel Ibarra", "especialidad": "Traumatología", "desde": "08:00", "hasta": "14:00"},
    {"nombre": "Dr. José Jiménez", "especialidad": "Endocrinología", "desde": "08:00", "hasta": "14:00"},
    {"nombre": "Dr. Isabel Martínez", "especialidad": "Ginecología", "desde": "10:00", "hasta": "16:00"},
    {"nombre": "Dr. Sergio Ruiz", "especialidad": "Medicina General", "desde": "10:00", "hasta": "16:00"},
    {"nombre": "Dr. Elena Torres", "especialidad": "Pediatría", "desde": "10:00", "hasta": "16:00"},
    {"nombre": "Dr. Ricardo López", "especialidad": "Otorrino", "desde": "10:00", "hasta": "16:00"},
    {"nombre": "Dr. Carmen Fernández", "especialidad": "Cardiología", "desde": "10:00", "hasta": "16:00"},
    {"nombre": "Dr. Francisco González", "especialidad": "Dermatología", "desde": "10:00", "hasta": "16:00"},
    {"nombre": "Dr. Patricia Pérez", "especialidad": "Neurología", "desde": "10:00", "hasta": "16:00"},
    {"nombre": "Dr. Martín Sánchez", "especialidad": "Psiquiatría", "desde": "10:00", "hasta": "16:00"},
    {"nombre": "Dr. Laura Rodríguez", "especialidad": "Traumatología", "desde": "10:00", "hasta": "16:00"},
    {"nombre": "Dr. Hugo González", "especialidad": "Endocrinología", "desde": "10:00", "hasta": "16:00"},
    {"nombre": "Dr. Claudia García", "especialidad": "Ginecología", "desde": "12:00", "hasta": "18:00"},
    {"nombre": "Dr. Alejandro Martínez", "especialidad": "Medicina General", "desde": "12:00", "hasta": "18:00"},
    {"nombre": "Dr. Susana Torres", "especialidad": "Pediatría", "desde": "12:00", "hasta": "18:00"},
    {"nombre": "Dr. Esteban López", "especialidad": "Otorrino", "desde": "12:00", "hasta": "18:00"},
    {"nombre": "Dr. Andrés Fernández", "especialidad": "Cardiología", "desde": "12:00", "hasta": "18:00"},
    {"nombre": "Dr. Victoria Sánchez", "especialidad": "Dermatología", "desde": "12:00", "hasta": "18:00"},
    {"nombre": "Dr. Iván Pérez", "especialidad": "Neurología", "desde": "12:00", "hasta": "18:00"},
    {"nombre": "Dr. Diana Ibarra", "especialidad": "Psiquiatría", "desde": "12:00", "hasta": "18:00"},
    {"nombre": "Dr. Felipe Jiménez", "especialidad": "Traumatología", "desde": "12:00", "hasta": "18:00"},
    {"nombre": "Dr. Ana Ruiz", "especialidad": "Endocrinología", "desde": "12:00", "hasta": "18:00"},
    {"nombre": "Dr. Teresa Díaz", "especialidad": "Ginecología", "desde": "14:00", "hasta": "20:00"},
    {"nombre": "Dr. Joaquín González", "especialidad": "Medicina General", "desde": "14:00", "hasta": "20:00"},
    {"nombre": "Dr. Lucía Rodríguez", "especialidad": "Pediatría", "desde": "14:00", "hasta": "20:00"},
    {"nombre": "Dr. Tomás Herrera", "especialidad": "Otorrino", "desde": "14:00", "hasta": "20:00"},
    {"nombre": "Dr. Paula Sánchez", "especialidad": "Cardiología", "desde": "14:00", "hasta": "20:00"},
    {"nombre": "Dr. Ricardo Torres", "especialidad": "Dermatología", "desde": "14:00", "hasta": "20:00"},
    {"nombre": "Dr. Isabel Pérez", "especialidad": "Neurología", "desde": "14:00", "hasta": "20:00"},
    {"nombre": "Dr. Sergio Ibarra", "especialidad": "Psiquiatría", "desde": "14:00", "hasta": "20:00"},
    {"nombre": "Dr. Rodrigo Jiménez", "especialidad": "Traumatología", "desde": "14:00", "hasta": "20:00"},
    {"nombre": "Dr. Marta González", "especialidad": "Endocrinología", "desde": "14:00", "hasta": "20:00"},
    {"nombre": "Dr. Juan Carlos López", "especialidad": "Ginecología", "desde": "16:00", "hasta": "22:00"},
    {"nombre": "Dr. Paula Martínez", "especialidad": "Medicina General", "desde": "16:00", "hasta": "22:00"},
    {"nombre": "Dr. Hugo Sánchez", "especialidad": "Pediatría", "desde": "16:00", "hasta": "22:00"},
    {"nombre": "Dr. Claudia Rodríguez", "especialidad": "Otorrino", "desde": "16:00", "hasta": "22:00"},
    {"nombre": "Dr. José Pérez", "especialidad": "Cardiología", "desde": "16:00", "hasta": "22:00"},
    {"nombre": "Dr. Laura Torres", "especialidad": "Dermatología", "desde": "16:00", "hasta": "22:00"},
    {"nombre": "Dr. Roberto González", "especialidad": "Neurología", "desde": "16:00", "hasta": "22:00"},
    {"nombre": "Dr. Isabel Ibarra", "especialidad": "Psiquiatría", "desde": "16:00", "hasta": "22:00"},
    {"nombre": "Dr. Marta Pérez", "especialidad": "Traumatología", "desde": "16:00", "hasta": "22:00"},
    {"nombre": "Dr. Luis Fernández", "especialidad": "Endocrinología", "desde": "16:00", "hasta": "22:00"},
    {"nombre": "Dr. Antonio López", "especialidad": "Ginecología", "desde": "18:00", "hasta": "22:00"},
    {"nombre": "Dr. Carolina González", "especialidad": "Medicina General", "desde": "18:00", "hasta": "22:00"},
    {"nombre": "Dr. Pedro Sánchez", "especialidad": "Pediatría", "desde": "18:00", "hasta": "22:00"},
    {"nombre": "Dr. Paula Díaz", "especialidad": "Otorrino", "desde": "18:00", "hasta": "22:00"},
    {"nombre": "Dr. Sergio Martínez", "especialidad": "Cardiología", "desde": "18:00", "hasta": "22:00"},
    {"nombre": "Dr. Fernando Rodríguez", "especialidad": "Dermatología", "desde": "18:00", "hasta": "22:00"},
    {"nombre": "Dr. Teresa Pérez", "especialidad": "Neurología", "desde": "18:00", "hasta": "22:00"},
    {"nombre": "Dr. Guillermo Ibarra", "especialidad": "Psiquiatría", "desde": "18:00", "hasta": "22:00"},
    {"nombre": "Dr. Alejandro Jiménez", "especialidad": "Traumatología", "desde": "18:00", "hasta": "22:00"},
    {"nombre": "Dr. Juan Hernández", "especialidad": "Endocrinología", "desde": "18:00", "hasta": "22:00"}
]

def key():
  return "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"

